version: '3.8'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "pwd123456!"
      MONGO_INITDB_DATABASE: shop
  microservice:
    image: msproductos:latest
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    environment:
      spring.config.location: "/application.yaml"
    volumes:
      - ./test/application.yaml:/application.yaml
    depends_on:
      - mongo
  test:
    image: mzegarra/csonictest
    volumes:
      - ./features:/usr/src/app/features
      - ./report:/usr/src/app/report
    depends_on:
      - mongo
      - microservice
      