microservice:
  path: /usr/local/Cursos/WebFlux/lab04/files
spring:
  data:
    mongodb:
      host: localhost
      username: root
      password: pwd123456!
      port: 27017
      database: shop
      authentication-database: admin