version: '3.8'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "pwd123456!"
      MONGO_INITDB_DATABASE: interfaces
  test:
    image: ubuntu
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongo