# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: VErificando código
        run: mvn -B verify
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          #context: .
          file: $PWD/src/main/docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: false
          tags: mzegarra/mservice1:latest        
